### ISSUE TITLE
swagger code gen id query parameter inconsistency

### ISSUE THREAD

**Issue by ayuksekkaya** [jezzsantos/saastack#45]
The generated swagger.json file is inconsistent with how the "id" parameter is showing up as query parameter in GET requests vs PATCH/PUT/DELETE requests which leads to tools like orval not functioning correctly when trying to auto create react-query hooks from the generated swagger.json.

Example for the swagger.json file created for ApiHost1. For PUT request to /cars/{Id}/maintain endpoint, the generated doc shows up like so:

``` 
    "/cars/{Id}/maintain": {
      "put": {
        "tags": [
          "CarsApi"
        ],
        "summary": "Schedules the car for maintenance for the specified period",
        "description": "(request type: ScheduleMaintenanceCarRequest)",
        "operationId": "ScheduleMaintenanceCar (Put)",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ScheduleMaintenanceCarRequest"
              }
            }
          }
        }
```

Whereas for get requests, for example: /cars/{Id} endpoint, the generated swagger.json shows up like so:

```
"get": {
        "tags": [
          "CarsApi"
        ],
        "summary": "Fetches the specified car",
        "description": "(request type: GetCarRequest)",
        "operationId": "GetCar",
        "parameters": [
          {
            "name": "Id",
            "in": "path",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          },
```

Where the id parameter is explicitly defined as path parameter.

Due to this I am getting an error while using orval to create react-query clients:

```
The path params id can't be found in parameters (ScheduleMaintenanceCar (Put))
    at /home/m/repos/saastack-react/node_modules/@orval/core/dist/index.js:46067:13
    at Array.map (<anonymous>)
    at getParams (/home/m/repos/saastack-react/node_modules/@orval/core/dist/index.js:46058:17)
```

@jezzsantos I am not sure if this is an orval problem or saastack problem per se, so I am posting it here to get your opinion on it as well.

**Comment by jezzsantos** [comment]
Thanks for reporting this, @ayuksekkaya,

Yes, I see what you mean.
Ideally, the `Id` parameter would be in the OpenAPI parameters collection rather than in the body of the request, as it is part of the route/path.

We shall fix this.

However, we have no good way to mark up other fields as parameters unless they appear in the route.

**Comment by ayuksekkaya** [comment]
Yes, I think as long as the parameters that are part of the route template template appear as path params in open api specs, that should be fine, since other fields would be coming from the body anyway, so they are not part of the path. 

Also, this is already working correctly for query params such as "limit", "offset" etc.

**Comment by ayuksekkaya** [comment]
@jezzsantos, thank you for pushing a fix this quick. So yes I see the "id" parameter as a path parameter now, but I am a bit confused on how we should be making non "GET" requests from a front end client. When I make a request like so:

PUT https://localhost:5001/cars/car_PeUaVtBuNkifeI6wBew4fQ/maintain
{
  "organizationId": "org_oemafdWXh0aox2BbNsEdcw",
  "fromUtc": "2024-08-12T03:42:20.533Z",
  "toUtc": "2024-08-14T03:42:20.533Z"
}

The request fails saying "id" is missing. Do we always need to leave the template as is?

Like when I am constructing the query in my front end client, do I always leave the template params in place like this:

PUT https://localhost:5001/cars/{Id}/maintain
{
  "organizationId": "org_oemafdWXh0aox2BbNsEdcw",
  "Id" : "car_PeUaVtBuNkifeI6wBew4fQ"
  "fromUtc": "2024-08-12T03:42:20.533Z",
  "toUtc": "2024-08-14T03:42:20.533Z"
}

Because only the second style works when I would expect first style to work as well. I read the docs, but I think this isn't clear.

**Comment by jezzsantos** [comment]
hmmm, @ayuksekkaya 

I can assure you that if you are just using a HTTP tool like POSTMAN, CURL or an Http file that you will have no problem making this API call like this:

```
PUT https://localhost:5001/cars/car_PeUaVtBuNkifeI6wBew4fQ/maintain
{
"organizationId": "org_oemafdWXh0aox2BbNsEdcw",
"fromUtc": "2024-08-12T03:42:20.533Z",
"toUtc": "2024-08-14T03:42:20.533Z"
}
```

Is the front-end client you are using generated from the OpenApi definitions?, and if so,  is the client seeing the `Id` in the POST body definition and enforcing some rule that you have to use it?


If that is the case, I guess we have nochoice but to remove the `Id` (in this case) form the schema of the request body.
Which can be done.

There is nothing in the docs about this problem, because it may only be a defect in the OpenApi schema.

btw: I see you are explicitly setting the `OrganizationId` in the request body. You actually should not have to specify that when you are providing a JWT token, unless you are accessing a specific organization. If you are accessing the same organization as the user default organization, then no need to specify the `OrganizationId`. It is a useful default.

**Comment by ayuksekkaya** [comment]
@jezzsantos, sorry I was using Insomnia to make the requests initially and this is what I was getting:

![image](https://github.com/user-attachments/assets/d2a92dce-8e61-4104-8a93-b543890af035)

Whereas when I do put the Id both in the body and in the path it works without any problems (ignore the 400 in this image as we see from the error message that it worked):

![image](https://github.com/user-attachments/assets/3f008884-50ec-46f1-897d-591fafe1943e)


I might be doing something wrong, but if I don't specify the "id" in the body, then it doesn't work for me. Although after your fix, I don't have a problem with doing it this way as long as the "id" also appears as a path param in OpenApi specs which it does currently. So if you want to close this issue, I think we can.

**Comment by jezzsantos** [comment]
No @ayuksekkaya you are NOT doing anything wrong.

Its not a problem with the OpenApi schema, it is something else.
There is something wrong! I am investigating now, please standby

**Comment by jezzsantos** [comment]
First off, I am absolutely stunned that this is a problem after so many months!

It would appear that variables in the route template (like `Id`) in either a POST, PUT or PATCH request, are not being fetched from the route and then being populated in the properties of the inbound request object, in the minimal API handler! 

An example request is defined like this. Notice the use of the `[global::Microsoft.AspNetCore.Mvc.FromBody]` attribute.

```c#
carsapiGroup.MapPut("/cars/{Id}/maintain",
                async (global::MediatR.IMediator mediator, [global::Microsoft.AspNetCore.Mvc.FromBody] global::Infrastructure.Web.Api.Operations.Shared.Cars.ScheduleMaintenanceCarRequest request) =>
                     await mediator.Send(request, global::System.Threading.CancellationToken.None))
                .RequireAuthorization("Token")
                .RequireCallerAuthorization("POLICY:{|Features|:{|Tenant|:[|tenant_paidtrial_features|]},|Roles|:{|Tenant|:[|tenant_member|]}}")
                .WithOpenApi(op =>
                    {
                        op.OperationId = "ScheduleMaintenanceCar (Put)";
                        op.Description = "(request type: ScheduleMaintenanceCarRequest)";
                        op.Responses.Clear();
                        return op;
                    });
```

This declaration was expected to be copying the `id` from the route into the `Id` property of the request class:

```c#
/// <summary>
///     Schedules the car for maintenance for the specified period
/// </summary>
[Route("/cars/{Id}/maintain", OperationMethod.PutPatch, AccessType.Token)]
[Authorize(Roles.Tenant_Member, Features.Tenant_PaidTrial)]
public class ScheduleMaintenanceCarRequest : TenantedRequest<GetCarResponse>
{
    public DateTime FromUtc { get; set; }

    [Required] public string? Id { get; set; }

    public DateTime ToUtc { get; set; }
}
```

But evidently, it does not work like expected!


We must ALSO have an issue in the `JsonClient` code that we use to test the API, since all the tests we have dont expose this problem either.

**Comment by ayuksekkaya** [comment]
I see yes that makes sense. Then if we fix that, we probably won't need to manipulate the open api filters to add it as path param either like in the most recent fix.

**Comment by jezzsantos** [comment]
Actually, I think we still need the fix for the OpenAPi. 

Im investigating binding to see how we can coerce minimal APIs to do the thing we need them to do.

**Comment by jezzsantos** [comment]
Turns out that:
* removing the `[FromBody]` attribute on PUT, POST, PATCH requests does not fix this issue.
* The last resort, [according to this](https://andrewlock.net/behind-the-scenes-of-minimal-apis-3-exploring-the-model-binding-logic-of-minimal-apis/#understanding-the-model-binding-precedence-in-minimal-apis),  is to [implement custom binding ](https://learn.microsoft.com/en-gb/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0#custom-binding) either with a static `TryParse` method or a static `BindingAsync` function, but in both these cases, we would need to implement a specific method in every request class, since those methods are typed to the final class type, and cannot be defined in base classes, which makes this approach too clumsy.

What we need is a framework level binding override to handle for all inbound requests.

**Comment by jezzsantos** [comment]
I have found a way to achieve this, but it does require redefining a request type.
For example, from this:
```c#
[Route("/cars/{Id}/maintain", OperationMethod.PutPatch, AccessType.Token)]
[Authorize(Roles.Tenant_Member, Features.Tenant_PaidTrial)]
public class ScheduleMaintenanceCarRequest : TenantedRequest<GetCarResponse>
{
    public DateTime FromUtc { get; set; }

    [Required] public string? Id { get; set; }

    public DateTime ToUtc { get; set; }
}
```
to this:
```c#
[Route("/cars/{Id}/maintain", OperationMethod.PutPatch, AccessType.Token)]
[Authorize(Roles.Tenant_Member, Features.Tenant_PaidTrial)]
public class ScheduleMaintenanceCarRequest : TenantedRequest<ScheduleMaintenanceCarRequest, GetCarResponse>
{
    public DateTime FromUtc { get; set; }

    [Required] public string? Id { get; set; }

    public DateTime ToUtc { get; set; }
}
```

But with this, we are able to define a custom `BindingAsync` function (on the base class) of all requests that solves this problem.
